nav:
  - Home: 'index.md'
  - User Documentation:
    - Getting Started: 'user/getting_started.md'
    - Installation: 'user/installation.md'
    - Developers Guide: 'user/developers_guide.md'
    # - Environment: 'user/environment.md'
  # - Server Documentation:
  #   - Getting started: 'server/getting_started.md'
  #   - Installation: 'server/installation.md'
  #   - Orchestration: 'server/orchestration.md'
  - Software Documentation:
    - Overview: 'software/overview.md'
    # - Interface RS485: 'software/interface_RS485.md'
    - DVL: 'software/dvl.md'
    - IMU: 'software/imu.md'
    - Vision: 'software/vision.md'
    - Navigation: 'software/proc_navigation.md'
  - Electrical Documentation:
    - Overview: 'electrical/overview.md'
    - Hydrophones: 'electrical/hydrophones.md'
    - DVL: 'electrical/dvl.md'
  - Mechanical Documentation:
    - Overview: 'mechanical/overview.md'
  - Proof of Concept:
    - 2018-2019: 'POC/2018_2019.md'
  - About AUV_IITK:
    - The Project: 'about/project.md'
    - Open Source Philosophy: 'about/open_source.md'
    - Sponsors of AUV IITK.: 'about/sponsors.md'

site_name: AUV IITK Documentation
repo_url: https://github.com/ShubhJain007/AUV_IITK_Documentation.git

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs
